
USE TESTDB
GO

-- bảng lớp học 
CREATE TABLE LopHoc(
    MaLop INT PRIMARY KEY NOT nULL,
	Lop VARCHAR(20)
)
GO

DROP TABLE LopHoc

-- bảng sinh viên 
CREATE TABLE SinhVien(
    TenSV NVARCHAR(50) NOT NULL,
	NgaySinh DATE NOT NULL,
	MaLop INT 
)
GO

INSERT INTO SinhVien VALUES (N'Nguyễn Văn A', '2002-01-01', 123, 3663)
INSERT INTO SinhVien VALUES (N'Nguyễn Văn B', '2001-01-02', 225, 6886)

INSERT INTO LopHoc VALUES (123, N'T2000A')
INSERT INTO LopHoc VALUES (225, 'T2005A')

SELECT * FROM LopHoc

SELECT * FROM SinhVien

ALTER TABLE SinhVien
    ADD ID INT NOT NULL

ALTER TABLE SinhVien
    ADD CONSTRAINT PK_ID PRIMARY KEY (ID)

ALTER TABLE SinhVien
    ADD CONSTRAINT FK_ML FOREIGN KEY (MaLop) REFERENCES LopHoc(MaLop)


